#!/usr/bin/env bash

CFG_DIR=~/.config/fat-runner
PID_FILE=$CFG_DIR/pid

mkdir -p $CFG_DIR

function become() {
  PID=$(find-nearest-ancestor spawn-and-stuff)
  if [ -z "$PID" ]; then
      exec shell-and-stuff "fat-runner become"
  fi

  echo $PID > $PID_FILE
}

function run() {
  LOCAL_PID=$(cat $PID_FILE)
  CMD_FILE=~/.config/spawn-and-stuff/$LOCAL_PID.command
  mkdir -p $(dirname $CMD_FILE)
  echo "$1" > $CMD_FILE
  kill -s USR1 $LOCAL_PID
}

if [ "$1" == "become" ]; then
  become
elif [ "$1" == "run" ]; then
  run "$2"
else
  echo "call the right shit, moron" >> /dev/stderr
fi
